name: {{cookiecutter.project_short_name}}
channels:
    - conda-forge
    - bioconda
dependencies:
    - python=3.11
    - snakemake-minimal=8.20.6
    {% if cookiecutter._add_cluster_infrastructure == True %}
    - snakemake-executor-plugin-slurm=0.11.2
    {% endif %}
