name: default
channels:
    - conda-forge
dependencies:
    - python=3.12
    - ipdb=0.13.13 # replaces default debugger with IPython debugger
    - numpy=2.3.0
    - pandas=2.3.0
    - matplotlib=3.10.3
    - seaborn=0.13.2
