name: Reproduction
on:
    schedule:
        - cron: "0 3 8 * *" # Runs every eighth day of the month at 3am.
    push:
        branches:
            - main
    pull_request:
defaults:
    run:
        shell: bash -l {0}
jobs:
    run_default_workflow:
        name: Reproduce the default demo analysis
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Setup cookiecutter environment
              uses: conda-incubator/setup-miniconda@v3
              with:
                auto-update-conda: true
                python-version: 3.11
                add-pip-as-python-dependency: true
            - name: Install cookiecutter
              run: pip install cookiecutter
            - name: Apply cookiecutter
              run: cookiecutter . --no-input --directory default
            - name: Setup Snakemake environment
              uses: conda-incubator/setup-miniconda@v3
              with:
                auto-update-conda: true
                python-version: 3.11
                activate-environment: reproducible-research-project
                environment-file: reproducible-research-project/environment.yaml
            - name: Reproduce results
              run: |
                cd reproducible-research-project
                snakemake
            - name: Generate DAG
              run: |
                cd reproducible-research-project
                snakemake dag
            - name: Archive results
              run: |
                cd reproducible-research-project
                snakemake archive
    run_cluster_workflow:
        name: Reproduce the cluster demo analysis (run locally only)
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Setup cookiecutter environment
              uses: conda-incubator/setup-miniconda@v3
              with:
                auto-update-conda: true
                python-version: 3.11
                add-pip-as-python-dependency: true
            - name: Install cookiecutter
              run: pip install cookiecutter
            - name: Apply cookiecutter
              run: cookiecutter . --no-input --directory cluster
            - name: Setup Snakemake environment
              uses: conda-incubator/setup-miniconda@v3
              with:
                auto-update-conda: true
                python-version: 3.11
                activate-environment: reproducible-research-project
                environment-file: reproducible-research-project/environment.yaml
            - name: Reproduce results
              run: |
                cd reproducible-research-project
                snakemake
            - name: Generate DAG
              run: |
                cd reproducible-research-project
                snakemake dag
            - name: Archive results
              run: |
                cd reproducible-research-project
                snakemake archive
